DATABASE_URI = ''
DATABASE_PORT = None
DATABASE_USER = 'postgres'
DATABASE_PW = 'password'
DATABASE_NAME = 'grid_calc_db'
DATABASE_ENGINE = 'postgresql'
DATABASE_CONNECTION_STRING = '{0}://{1}:{2}@{3}:{4}/{5}'.format(DATABASE_ENGINE, DATABASE_USER, DATABASE_PW, DATABASE_URI, DATABASE_PORT, DATABASE_NAME)